version: '3'
services:
  app-traffic-simulator:
    image: golang:1.19
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
      app-worker:
        condition: service_started
    links:
      - redis
    volumes:
      - ../../:/app
      - $HOME/go/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run ./cqrs/example/cmd/trafficsim/main.go
    environment:
      SIMULATE_RPS: 100

  app-worker:
    image: golang:1.19
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    links:
      - redis
    volumes:
      - ../../:/app
      - $HOME/go/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run ./cqrs/example/cmd/app/main.go
    deploy:
      mode: replicated
      replicas: 10 # don't use more than 10 replicas on a single node
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379